pub mod roman_numeral_comparison;
pub mod caesar_cypher;
pub mod reverse_factorial;
pub mod next_palindrome;
pub mod fibonacci_ish_sequence;
pub mod letter_sum_value;
pub mod pancake_sort;
pub mod abacaba_sequence;
pub mod yahtzee_scoring;